### ISSUE TITLE
Duplicate book

### ISSUE THREAD

**Issue by bick88** [Outurnate/WarpBook#9]
Would it be possible to add a way to copy a book with its pages to have a copy in case you lose the book?
Thanks.

**Comment by Outurnate** [comment]
It's an idea I've played with before, but it has the issue of cost.  If you copy a 30 page book to a blank one, you just got 30 free pages.  If there's a nice mechanic to deal with that, I'm all ears

**Comment by psychofad** [comment]
I know this was posted a while ago, but I like this idea.  Perhaps you could make a block that has a slot for the book that you wish to copy, when you put it in it will request that you add the amount of pages it finds in the original book and provide it with a fresh warp book, for the cost of a configurable amount of XP per page it will make a copy of the book once all of the required materials are inserted and a confirm button is pressed.

Alternatively, you could add the ability to store unbound pages into a warp book, and have the player place a book with the pages already inserted into the block mentioned above.  If you use this idea, it would also be nice if you could set unbound pages while they are still inserted in a warp book so there would be no need to remove one to set a warp location.  The button would read Unbound until it was clicked and then it would present the familiar naming gui for you to name it accordingly.

Just some ideas, love your mod, haven't made a pack without it since I discovered it.  Thank You!

**Comment by Outurnate** [comment]
A block is probably the best way.  Putting unbound pages in the book and binding them inside seems natural enough...the code will need a good refactor to support it

I'll do it for the next update

**Comment by Outurnate** [comment]
Backups might be nice too

**Comment by psychofad** [comment]
Will this only be in the 1.8.9/1.9 versions or can we hope to see it in 1.7.10 as well?  I know what a hassle it is to maintain so many versions, but my server is just not ready to make the switch yet, but I understand either way!  Thanks!

**Comment by Outurnate** [comment]
I get it.  I'm still on 1.7.10 myself.  Depending on how much under the hood work I do I may backport.  Right now there's a chance I'll break NBT compatibility with the older books, so backporting may not be ideal

**Comment by Outurnate** [comment]
Good news, there won't be a complete NBT break.  Pages will need to be upgraded.  I will add a mechanic for this

When I finish, I will see about cherry-picking the changes into 1.7.10

**Comment by Outurnate** [comment]
This feature is complete in the current build.  I'll be releasing a beta today or tomorrow

**Comment by psychofad** [comment]
Just curious, will you be able to implement any of this in the 1.7.10 version?  No worries if you can't, but reading the changelog on CurseForge makes me a bit jealous of the 1.8 users :P

**Comment by Outurnate** [comment]
Unfortunately, no.  I made a ton of under-the-hood changes that are required for the teleporter/cloner to work

Any way I can make 1.8 look better is a win for me :).  I expect to receive a few bug reports, the I will do a straight port to 1.9
